/**
 * Weather Forecast API
 * Weather API application that allows users to subscribe to weather updates for their city.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscribeRequest { 
    /**
     * Email address to subscribe
     */
    email: string;
    /**
     * City for weather updates
     */
    city: string;
    /**
     * Frequency of updates (hourly or daily)
     */
    frequency: SubscribeRequest.FrequencyEnum;
}
export namespace SubscribeRequest {
    export type FrequencyEnum = 'hourly' | 'daily';
    export const FrequencyEnum = {
        Hourly: 'hourly' as FrequencyEnum,
        Daily: 'daily' as FrequencyEnum
    };
}


