/**
 * Weather Forecast API
 * Weather API application that allows users to subscribe to weather updates for their city.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Weather { 
    /**
     * Current temperature
     */
    temperature?: number;
    /**
     * Current humidity percentage
     */
    humidity?: number;
    /**
     * Weather description
     */
    description?: string;
}

